project:
  type: book
  output-dir: docs

book:
  title: "Від нуля до Python Data Scientist"
  author:
    - name: Ігор Мірошниченко
      orcid: 0000-0002-1307-7889
      email: ihor.miroshnychenko@kneu.ua
  description: Книга-конспект матеріалів
  body-header: | 
    [![Data Miorsh](https://img.shields.io/badge/Telegram-2CA5E0?style=for-the-badge&logo=telegram&logoColor=white)](https://t.me/araprof) [![Ihor Miroshnychenko](https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white)](https://www.linkedin.com/in/ihormiroshnychenko/) [![Youtube](https://img.shields.io/badge/YouTube-FF0000?style=for-the-badge&logo=youtube&logoColor=white)](https://www.youtube.com/@datamirosh) [![Monobank](https://img.shields.io/badge/sponsor-30363D?style=for-the-badge&logo=GitHub-Sponsors&logoColor=#white)](https://send.monobank.ua/jar/3rgj2uzZTs) 
  body-footer: | 
    [![Data Miorsh](https://img.shields.io/badge/Telegram-2CA5E0?style=for-the-badge&logo=telegram&logoColor=white)](https://t.me/araprof) [![Ihor Miroshnychenko](https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white)](https://www.linkedin.com/in/ihormiroshnychenko/) [![Youtube](https://img.shields.io/badge/YouTube-FF0000?style=for-the-badge&logo=youtube&logoColor=white)](https://www.youtube.com/@datamirosh) [![Monobank](https://img.shields.io/badge/sponsor-30363D?style=for-the-badge&logo=GitHub-Sponsors&logoColor=#white)](https://send.monobank.ua/jar/3rgj2uzZTs) 
  # margin-header: |
  #   ![](/cover.png)
  # margin-footer: |
  #   ![](/cover.png)
  keyword: python, data science, machine learning, data analysis, data visualization, statistics, sql, pandas, numpy, matplotlib, seaborn, scikit-learn, plotly, pyspark
  date: today
  date-format: iso
  # cover-image: monobanka.jpg
  favicon: cover.png
  repo-url: https://github.com/Aranaur/py4ds
  url: https://aranaur.github.io/py4ds/
  repo-branch: main
  repo-actions: [edit, issue, source]
  sidebar: 
    # background: "#F5F5F5"
    logo: cover.png
    search: true
  sharing: [twitter, facebook, linkedin]
  google-analytics: 'G-0C9TJBF3C5'
  chapters:
    - index.qmd
    - text: "---"
    - part: chapters/python/python.qmd
      chapters: 
      - chapters/python/python_basics.qmd
      - chapters/python/python_conditionals.qmd
      - chapters/python/python_loops.qmd
      - chapters/python/python_exceptions.qmd
      - chapters/python/python_libraries.qmd
      - chapters/python/python_unit_tests.qmd
      - chapters/python/python_files_io.qmd
      - chapters/python/python_regex.qmd
      - chapters/python/python_oop.qmd
      - chapters/python/python_et_cetera.qmd
      - chapters/python/python_functions.qmd
      - chapters/python/python_exercises.qmd
      - chapters/python/python_questions.qmd
    # - text: "---"
    # - part: math4ds.qmd
    #   chapters: 
    #   - math4ds_analysis_I.qmd
      # - math4ds_linear_algebra.qmd
      # - math4ds_statistics.qmd
      # - math4ds_probability.qmd
      # - math4ds_exercises.qmd
      # - math4ds_questions.qmd
    - text: "---"
    - part: chapters/sql/sql.ipynb
      chapters: 
      - chapters/sql/sql_basics.ipynb
      - chapters/sql/sql_filter.ipynb
      - chapters/sql/sql_agg.ipynb
      - chapters/sql/sql_groupby.ipynb
      - chapters/sql/sql_subquery.ipynb
      - chapters/sql/sql_join.ipynb
      - chapters/sql/sql_window.ipynb
      - chapters/sql/sql_analytic.ipynb
      - chapters/sql/sql_metrics.ipynb
    - text: "---"
    - chapters/quarto.qmd

comments:
    giscus:
      repo: aranaur/py4ds
    
language: _language-ukr.yml

bibliography: references.bib

engine: knitr

format:
  html:
    df-print: kable
    fig-align: center
    code-overflow: scroll
    code-link: true
    code-line-numbers: false
    code-fold: false
    theme:
      light: [cosmo, theme.scss]
      # dark: [superhero, theme.scss]
    # backgroundcolor: "#F5F5F5"
include-in-header:
  text: |
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">

filters:
  - line-highlight
