project:
  type: book
  output-dir: docs

book:
  title: "Python в науці про дані"
  author: "Ігор Мірошниченко"
  date: today
  date-format: iso
  chapters:
    - index.qmd
    - 01_intro.qmd
    - 02_type_and_str.qmd
    - 03_control_constructs.qmd
    - text: "---"
    - part: 05_sql.qmd
      chapters: 
        - 05_01_basics.qmd
        - 05_02_filtering.qmd
        - 05_03_aggregation.qmd
    - text: "---"
    - 04_quarto.qmd
    - references.qmd
    
language: _language-ukr.yml

bibliography: references.bib

format:
  html:
    df-print: kable
    theme:
      light: cosmo
      dark: superhero

execute:
  warning: false
  # cache: true