project:
  type: book
  output-dir: docs

book:
  title: "Python в науці про дані"
  author: "Ігор Мірошниченко"
  description: Книга-конспект матеріалів з курсу “Python в науці про дані”.
  keyword: polars, pandas, python, dataframe, performance, data science, data engineering
  date: today
  date-format: iso
  # cover-image: cover.png
  favicon: cover.png
  repo-url: https://github.com/Aranaur/py4ds
  url: https://aranaur.github.io/py4ds/
  sidebar: 
    # background: "#F5F5F5"
    logo: cover.png
    search: true
  sharing: [twitter, facebook, linkedin]
  google-analytics: 'G-0C9TJBF3C5'
  chapters:
    - index.ipynb
    - text: "---"
    - part: sql.ipynb
      chapters: 
      - sql_basics.ipynb
      - sql_filtering.ipynb
    - text: "---"
    - quarto.ipynb
    
language: _language-ukr.yml

bibliography: references.bib

format:
  html:
    df-print: kable
    code-overflow: wrap
    code-link: true
    theme:
      light: cosmo
      dark: superhero
    # backgroundcolor: "#F5F5F5"
