project:
  type: book
  output-dir: docs

book:
  title: "Python в науці про дані"
  author: "Ігор Мірошниченко"
  date: "2022-10-22"
  chapters:
    - index.qmd
    - 01_intro.qmd
    - 02_type_and_str.qmd
    - 03_control_constructs.qmd
    - references.qmd
    
language: _language-ukr.yml

bibliography: references.bib

format:
  html:
    theme:
      light: cosmo
      dark: superhero