project:
  type: book
  output-dir: docs

book:
  title: "Python в науці про дані"
  author: "Ігор Мірошниченко"
  description: Книга-конспект матеріалів з курсу “Python в науці про дані”.
  keyword: polars, pandas, python, dataframe, performance, data science, data engineering
  date: today
  date-format: iso
  # cover-image: cover.png
  favicon: cover.png
  repo-url: https://github.com/Aranaur/py4ds
  url: https://aranaur.github.io/py4ds/
  sidebar: 
    # background: "#F5F5F5"
    logo: cover.png
    search: true
  sharing: [twitter, facebook, linkedin]
  google-analytics: 'G-0C9TJBF3C5'
  chapters:
    - index.qmd
    - 01_intro.qmd
    - 02_type_and_str.qmd
    - 03_control_constructs.qmd
    - text: "---"
    - part: 05_sql.qmd
      chapters: 
        - 05_01_basics.qmd
        - 05_02_filtering.qmd
        - 05_03_aggregation.qmd
    - text: "---"
    - 04_quarto.qmd
    - references.qmd
    
language: _language-ukr.yml

bibliography: references.bib

format:
  html:
    code-overflow: wrap
    code-link: true
    theme:
      light: cosmo
      dark: superhero
    # backgroundcolor: "#F5F5F5"
