project:
  type: book
  output-dir: docs

book:
  title: "Python в науці про дані"
  author: "Ігор Мірошниченко"
  date: "2022-10-22"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
    
language: custom.yml

bibliography: references.bib

format:
  html:
    theme: cosmo