project:
  type: book
  output-dir: docs

book:
  title: "Від нуля до Python Data Scientist"
  author:
    - name: Ігор Мірошниченко
      orcid: 0000-0002-1307-7889
      email: ihor.miroshnychenko@kneu.ua
  description: Книга-конспект матеріалів
  body-header: | 
    [![Data Miorsh](https://img.shields.io/badge/Telegram-2CA5E0?style=for-the-badge&logo=telegram&logoColor=white)](https://t.me/araprof) [![Ihor Miroshnychenko](https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white)](https://www.linkedin.com/in/ihormiroshnychenko/) [![Youtube](https://img.shields.io/badge/YouTube-FF0000?style=for-the-badge&logo=youtube&logoColor=white)](https://www.youtube.com/@datamirosh) [![Monobank](https://img.shields.io/badge/sponsor-30363D?style=for-the-badge&logo=GitHub-Sponsors&logoColor=#white)](https://send.monobank.ua/jar/3rgj2uzZTs) 
  body-footer: | 
    [![Data Miorsh](https://img.shields.io/badge/Telegram-2CA5E0?style=for-the-badge&logo=telegram&logoColor=white)](https://t.me/araprof) [![Ihor Miroshnychenko](https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white)](https://www.linkedin.com/in/ihormiroshnychenko/) [![Youtube](https://img.shields.io/badge/YouTube-FF0000?style=for-the-badge&logo=youtube&logoColor=white)](https://www.youtube.com/@datamirosh) [![Monobank](https://img.shields.io/badge/sponsor-30363D?style=for-the-badge&logo=GitHub-Sponsors&logoColor=#white)](https://send.monobank.ua/jar/3rgj2uzZTs) 
  # margin-header: |
  #   ![](/cover.png)
  # margin-footer: |
  #   ![](/cover.png)
  keyword: python, data science, machine learning, data analysis, data visualization, statistics, sql, pandas, numpy, matplotlib, seaborn, scikit-learn, plotly, pyspark
  date: today
  date-format: iso
  # cover-image: monobanka.jpg
  favicon: cover.png
  repo-url: https://github.com/Aranaur/py4ds
  url: https://aranaur.github.io/py4ds/
  repo-branch: main
  repo-actions: [edit, issue, source]
  sidebar: 
    # background: "#F5F5F5"
    logo: cover.png
    search: true
  sharing: [twitter, facebook, linkedin]
  google-analytics: 'G-0C9TJBF3C5'
  chapters:
    - index.qmd
    - text: "---"
    - part: python.qmd
      chapters: 
      - python_basics.qmd
      - python_list_set.qmd
      - python_dict.qmd
      - python_strings.qmd
      - python_if.qmd
      - python_loops.qmd
      - python_functions.qmd
      - python_exercises.qmd
      - python_questions.qmd
    - text: "---"
    - part: sql.ipynb
      chapters: 
      - sql_basics.ipynb
      - sql_filter.ipynb
      - sql_agg.ipynb
      - sql_groupby.ipynb
      - sql_subquery.ipynb
      - sql_join.ipynb
      - sql_window.ipynb
      - sql_analytic.ipynb
      - sql_metrics.ipynb
    - text: "---"
    - quarto.qmd

comments:
    giscus:
      repo: aranaur/py4ds
    
language: _language-ukr.yml

bibliography: references.bib

format:
  html:
    df-print: kable
    code-overflow: scroll
    code-link: true
    code-line-numbers: true
    code-fold: false
    theme:
      light: cosmo
      dark: superhero
    # backgroundcolor: "#F5F5F5"

launch_buttons:
  colab_url: "https://colab.research.google.com"
