# Математика для DS

## Навіщо потрібно знати математику у Data Science?

По-перше, нам потрібно навчитися **мислити абстрактно**, до того ж абсолютно не важливо, чим саме ми займаємося, інженеримо моделі машинного навчання, займаємося класичною дата аналітикою або ми там узагалі будуємо дашборди в MBA аналітики, так чи інакше дуже важливо вміти мислити абстрактно. Наприклад, коли ми спілкуємося із замовником і намагаємося його бізнес-вимоги перекладати технічною мовою, це теж певна процедура, яка вимагає абстрактного мислення, і слава богу, нам з вами пощастило, тому що математика - це найяскравіший і, напевно, найефективніший спосіб, щоб прокачати абстрактне мислення. По-друге, щоб читати сучасні статті та знайомитися з новими підходами обробки даних, нам, напевно, потрібно вміти в жорсткий математичний аналіз, ну або хоча б в якийсь базовий, який вивчається на перших курсах у вищих навчальних закладах. Чому? Та просто-напросто тому, що в сучасному світі моделі настільки складно влаштовані, що без якихось математичних основ зрозуміти, як вони працюють, навіть інтуїтивно, це просто супер-упер складно. І, нарешті, коли ми говоримо вже про працевлаштування, там теж дуже важливо демонструвати свої навички в математиці.